// GENERATED by _system/build-config.py. Do not edit.
// source: sections
window.DECK_CONFIG = {
  "meta": {
    "transitionMs": 550,
    "subviewMs": 450,
    "heightenedMs": 900,
    "easing": "cubic-bezier(0.65, 0, 0.35, 1)"
  },
  "sections": [
    {
      "id": "welcome",
      "order": 1,
      "title": "Welcome",
      "scale": 1.0,
      "heightened": false,
      "holdText": false,
      "stack": false,
      "subviews": [
        {
          "id": "main",
          "layout": "title",
          "eyebrow": "Contract/CR-Request approval",
          "heading": "From Request to Resolution",
          "body": "From system data to signature-ready. Data becomes documentation. Decisions stay human.",
          "tall": false,
          "asset": null
        }
      ]
    },
    {
      "id": "agenda",
      "order": 2,
      "title": "Agenda",
      "scale": 1.0,
      "heightened": false,
      "holdText": false,
      "stack": false,
      "subviews": [
        {
          "id": "main",
          "layout": "agenda",
          "eyebrow": "",
          "heading": "What we'll walk through",
          "body": "",
          "tall": false,
          "items": [
            "The Monitor - See every Workflow run in one place",
            "Today's Process - How contracts and CR-Requests are created today",
            "The New Process - From start to finish",
            "The Final Contract - Signed, stored, and shared"
          ],
          "asset": null
        }
      ]
    },
    {
      "id": "the-monitor",
      "order": 3,
      "title": "The monitor",
      "scale": 1.0,
      "heightened": false,
      "holdText": false,
      "stack": true,
      "subviews": [
        {
          "id": "a",
          "layout": "image-stack",
          "eyebrow": "The automation monitor",
          "heading": "End-to-End Workflow Monitoring",
          "body": "Track each workflow from start to finish, monitor its health, and quickly identify where something needs attention.",
          "tall": false,
          "stackIndex": 0,
          "stackCount": 7,
          "asset": {
            "type": "image",
            "src": "assets/show/automation-monitor-board.png",
            "caption": null,
            "autoplay": false
          }
        },
        {
          "id": "b",
          "layout": "image-stack",
          "eyebrow": "The automation monitor",
          "heading": "Running",
          "body": "The Workflow is currently in progress and moving through the required process steps.",
          "tall": false,
          "stackIndex": 1,
          "stackCount": 7,
          "asset": {
            "type": "image",
            "src": "assets/show/automation-monitor-running.png",
            "caption": null,
            "autoplay": false
          }
        },
        {
          "id": "c",
          "layout": "image-stack",
          "eyebrow": "The automation monitor",
          "heading": "Pending approval",
          "body": "The workflow has reached an approval step and will continue once the required Human-made decision is received.",
          "tall": false,
          "stackIndex": 2,
          "stackCount": 7,
          "asset": {
            "type": "image",
            "src": "assets/show/automation-monitor-pending-approval.png",
            "caption": null,
            "autoplay": false
          }
        },
        {
          "id": "d",
          "layout": "image-stack",
          "eyebrow": "The automation monitor",
          "heading": "Awaiting signature",
          "body": "The document has been sent and is waiting for the required signature before continuing.",
          "tall": false,
          "stackIndex": 3,
          "stackCount": 7,
          "asset": {
            "type": "image",
            "src": "assets/show/automation-monitor-awaiting-signature.png",
            "caption": null,
            "autoplay": false
          }
        },
        {
          "id": "e",
          "layout": "image-stack",
          "eyebrow": "The automation monitor",
          "heading": "Succeeded",
          "body": "Contract signed, register updated. Green means the work was really delivered, not that the code ran.",
          "tall": false,
          "stackIndex": 4,
          "stackCount": 7,
          "asset": {
            "type": "image",
            "src": "assets/show/automation-monitor-succeeded.png",
            "caption": null,
            "autoplay": false
          }
        },
        {
          "id": "f",
          "layout": "image-stack",
          "eyebrow": "The automation monitor",
          "heading": "Failed",
          "body": "The workflow encountered an issue. The affected step and system-provided reason will be clearly identified.",
          "tall": false,
          "stackIndex": 5,
          "stackCount": 7,
          "asset": {
            "type": "image",
            "src": "assets/show/automation-monitor-failed.png",
            "caption": null,
            "autoplay": false
          }
        },
        {
          "id": "g",
          "layout": "image-stack",
          "eyebrow": "The automation monitor",
          "heading": "Failed, and dealt with",
          "body": "The issue has been acknowledged and addressed, while remaining visible for transparency and tracking.",
          "tall": false,
          "stackIndex": 6,
          "stackCount": 7,
          "asset": {
            "type": "image",
            "src": "assets/show/automation-monitor-failed-completed.png",
            "caption": null,
            "autoplay": false
          }
        }
      ]
    },
    {
      "id": "today",
      "order": 4,
      "title": "Today",
      "scale": 1.0,
      "heightened": false,
      "holdText": false,
      "stack": false,
      "subviews": [
        {
          "id": "main",
          "layout": "title",
          "eyebrow": "Part one",
          "heading": "Today, One Request Starts a Chain of Manual Work",
          "body": "One customer request triggers multiple rounds of data entry, approvals, document creation, handoffs, and signatures. The same information is repeatedly entered, reviewed, sent, signed, and tracked across the process and the project or change can't begin until the entire chain is complete.",
          "tall": false,
          "asset": null
        }
      ]
    },
    {
      "id": "the-new-process",
      "order": 5,
      "title": "The new process",
      "scale": 1.0,
      "heightened": false,
      "holdText": false,
      "stack": false,
      "subviews": [
        {
          "id": "main",
          "layout": "title",
          "eyebrow": "Part two",
          "heading": "The new process",
          "body": "Enter Once. Automate the Rest.",
          "tall": false,
          "asset": null
        }
      ]
    },
    {
      "id": "the-way-in",
      "order": 6,
      "title": "The way in",
      "scale": 1.0,
      "heightened": false,
      "holdText": false,
      "stack": false,
      "subviews": [
        {
          "id": "main",
          "layout": "animation",
          "eyebrow": "The manual effort",
          "heading": "Drop the system data into the SharePoint folder",
          "body": "That's it. No AI, no additional tooling, the workflow takes over from there.",
          "tall": false,
          "animation": "sharepoint-drop",
          "asset": null
        }
      ]
    },
    {
      "id": "extract-and-fill",
      "order": 7,
      "title": "Extract and fill",
      "scale": 1.0,
      "heightened": false,
      "holdText": false,
      "stack": false,
      "subviews": [
        {
          "id": "a",
          "layout": "asset-pair",
          "eyebrow": "Part two",
          "heading": "One Input. Automation Does the Rest.",
          "body": "Enter the required information in the system, export the PDF. Drop it in the SharePoint Folder.",
          "tall": false,
          "asset": {
            "type": "image",
            "src": "assets/show/company-information-sheet.png",
            "caption": "What went in",
            "autoplay": false
          },
          "assets": [
            {
              "type": "image",
              "src": "assets/show/company-information-sheet.png",
              "caption": "What went in",
              "autoplay": false
            },
            {
              "type": "image",
              "src": "assets/show/draft-contract.png",
              "caption": "What came out",
              "autoplay": false
            }
          ]
        },
        {
          "id": "b",
          "layout": "animation",
          "eyebrow": "Part two",
          "heading": "No duplicate manual effort",
          "body": "The Automation extracts the data already entered, maps it to the right fields, and builds the customer document.",
          "tall": false,
          "animation": "extract-fill",
          "asset": null
        }
      ]
    },
    {
      "id": "the-approval",
      "order": 8,
      "title": "The approval",
      "scale": 1.0,
      "heightened": false,
      "holdText": false,
      "stack": false,
      "subviews": [
        {
          "id": "a",
          "layout": "single-asset",
          "eyebrow": "The human decision",
          "heading": "Everything is brought together in one place for review",
          "body": "The user is notified via Teams that the generated document and all extracted values are ready for review.",
          "tall": false,
          "asset": {
            "type": "image",
            "src": "assets/show/teams-approval-card.png",
            "caption": null,
            "autoplay": false
          }
        },
        {
          "id": "b",
          "layout": "single-asset",
          "eyebrow": "The human decision",
          "heading": "Adjust Before You Approve",
          "body": "Any extracted value can be updated directly during the review. The final approved values, whether unchanged or corrected, are then used to generate the customer document.",
          "tall": false,
          "asset": {
            "type": "image",
            "src": "assets/show/teams-approval-editing.png",
            "caption": null,
            "autoplay": false
          }
        },
        {
          "id": "c",
          "layout": "single-asset",
          "eyebrow": "The human decision",
          "heading": "Or, Take It to Email",
          "body": "The same review and approval can be completed via email when preferred. A secure, one-time link takes the user directly to the review page.",
          "tall": "full",
          "asset": {
            "type": "image",
            "src": "assets/show/email-approval-page.png",
            "caption": null,
            "autoplay": false
          }
        }
      ]
    },
    {
      "id": "the-signature",
      "order": 9,
      "title": "The signature",
      "scale": 1.0,
      "heightened": true,
      "holdText": false,
      "stack": false,
      "subviews": [
        {
          "id": "a",
          "layout": "single-asset",
          "eyebrow": "The customer experience",
          "heading": "Direct Access.",
          "body": "No downloading attachments, no additional access rights for an account, app, or installation required. The full document is ready to review, with four clear steps guiding the user through the process.",
          "tall": true,
          "asset": {
            "type": "image",
            "src": "assets/show/signing-page.png",
            "caption": null,
            "autoplay": false
          }
        },
        {
          "id": "b",
          "layout": "single-asset",
          "eyebrow": "The customer experience",
          "heading": "Signature, Built In.",
          "body": "Customers sign directly within the experience from anywhere, using a mouse, finger, or stylus, removing the need for additional e-signature tools and their associated licensing costs.",
          "tall": false,
          "asset": {
            "type": "image",
            "src": "assets/show/signing-draw.gif",
            "caption": null,
            "autoplay": false
          }
        },
        {
          "id": "c",
          "layout": "single-asset",
          "eyebrow": "The customer experience",
          "heading": "Sign Your Way",
          "body": "Prefer a handwritten signature? Simply upload a photo of it. The workflow extracts the signature and places it cleanly into the document.",
          "tall": false,
          "asset": {
            "type": "image",
            "src": "assets/show/signing-upload.gif",
            "caption": null,
            "autoplay": false
          }
        },
        {
          "id": "d",
          "layout": "single-asset",
          "eyebrow": "The customer experience",
          "heading": "Agreement, Confirmed",
          "body": "With the final confirmation, the agreement is complete. The Automation captures the reference, signer, and exact timestamp, creating a clear record of who agreed and when.",
          "tall": false,
          "asset": {
            "type": "image",
            "src": "assets/show/signing-approve.gif",
            "caption": null,
            "autoplay": false
          }
        }
      ]
    },
    {
      "id": "delivered",
      "order": 10,
      "title": "Delivered",
      "scale": 1.0,
      "heightened": false,
      "holdText": false,
      "stack": false,
      "subviews": [
        {
          "id": "a",
          "layout": "single-asset",
          "eyebrow": "Signed. Sent. Complete.",
          "heading": "Everyone receives a final copy",
          "body": "The completed contract is sent directly to both the customer and the process initiator.",
          "tall": false,
          "asset": {
            "type": "image",
            "src": "assets/show/signed-contract.png",
            "caption": null,
            "autoplay": false
          }
        },
        {
          "id": "b",
          "layout": "single-asset",
          "eyebrow": "Signed. Sent. Complete.",
          "heading": "Keep the right people informed",
          "body": "Additional contacts, such as Account Managers or the GISO team can be automatically copied on the final notification, ensuring everyone who needs to know is informed once the process is complete.",
          "tall": false,
          "asset": {
            "type": "image",
            "src": "assets/show/signed-contract.png",
            "caption": null,
            "autoplay": false
          }
        }
      ]
    },
    {
      "id": "close",
      "order": 11,
      "title": "Close",
      "scale": 1.0,
      "heightened": false,
      "holdText": false,
      "stack": false,
      "subviews": [
        {
          "id": "main",
          "layout": "points",
          "eyebrow": "",
          "heading": "IMAGINE",
          "body": "",
          "tall": false,
          "items": [
            "Connected to CRM",
            "Connected to SwoDP",
            "Connected to the GISO ticket system"
          ],
          "asset": null
        }
      ]
    }
  ]
};
