// GENERATED by _system/build-config.py. Do not edit.
// source: sections
window.DECK_CONFIG = {
  "meta": {
    "transitionMs": 550,
    "subviewMs": 450,
    "heightenedMs": 900,
    "easing": "cubic-bezier(0.65, 0, 0.35, 1)"
  },
  "sections": [
    {
      "id": "welcome",
      "order": 1,
      "title": "Welcome",
      "scale": 1.0,
      "heightened": false,
      "holdText": false,
      "stack": false,
      "subviews": [
        {
          "id": "main",
          "layout": "title",
          "eyebrow": "Contract approval",
          "heading": "From sheet to signature",
          "body": "A company information sheet goes in. A signed contract comes out. The two decisions that matter are still made by people.",
          "asset": null
        }
      ]
    },
    {
      "id": "agenda",
      "order": 2,
      "title": "Agenda",
      "scale": 1.0,
      "heightened": false,
      "holdText": false,
      "stack": false,
      "subviews": [
        {
          "id": "main",
          "layout": "agenda",
          "eyebrow": "",
          "heading": "What we will walk through",
          "body": "",
          "items": [
            "The monitor, where every run shows itself",
            "How a contract gets made today",
            "The new process, start to finish",
            "The signed contract, and who gets it"
          ],
          "asset": null
        }
      ]
    },
    {
      "id": "the-monitor",
      "order": 3,
      "title": "The monitor",
      "scale": 1.0,
      "heightened": false,
      "holdText": false,
      "stack": true,
      "subviews": [
        {
          "id": "a",
          "layout": "image-stack",
          "eyebrow": "The automation monitor",
          "heading": "Every run, one row",
          "body": "One line per run, grouped by what it is waiting for. Anything red sits at the top.",
          "stackIndex": 0,
          "stackCount": 7,
          "asset": {
            "type": "image",
            "src": "assets/show/automation-monitor-board.png",
            "caption": null,
            "autoplay": false
          }
        },
        {
          "id": "b",
          "layout": "image-stack",
          "eyebrow": "The automation monitor",
          "heading": "Running",
          "body": "The step it is on, out of how many, and the time it last moved. It updates while you watch it.",
          "stackIndex": 1,
          "stackCount": 7,
          "asset": {
            "type": "image",
            "src": "assets/show/automation-monitor-running.png",
            "caption": null,
            "autoplay": false
          }
        },
        {
          "id": "c",
          "layout": "image-stack",
          "eyebrow": "The automation monitor",
          "heading": "Pending approval",
          "body": "Step 4 of 9, and it will sit there until a person answers. Waiting is not failing.",
          "stackIndex": 2,
          "stackCount": 7,
          "asset": {
            "type": "image",
            "src": "assets/show/automation-monitor-pending-approval.png",
            "caption": null,
            "autoplay": false
          }
        },
        {
          "id": "d",
          "layout": "image-stack",
          "eyebrow": "The automation monitor",
          "heading": "Awaiting signature",
          "body": "When the link went out, and how long it has been waiting. Two days and three hours, on this one.",
          "stackIndex": 3,
          "stackCount": 7,
          "asset": {
            "type": "image",
            "src": "assets/show/automation-monitor-awaiting-signature.png",
            "caption": null,
            "autoplay": false
          }
        },
        {
          "id": "e",
          "layout": "image-stack",
          "eyebrow": "The automation monitor",
          "heading": "Succeeded",
          "body": "Contract signed, register updated. Green means the work was really delivered, not that the code ran.",
          "stackIndex": 4,
          "stackCount": 7,
          "asset": {
            "type": "image",
            "src": "assets/show/automation-monitor-succeeded.png",
            "caption": null,
            "autoplay": false
          }
        },
        {
          "id": "f",
          "layout": "image-stack",
          "eyebrow": "The automation monitor",
          "heading": "Failed",
          "body": "The step it died on and the reason in the words the service gave. Word Online refused the document, and it says so.",
          "stackIndex": 5,
          "stackCount": 7,
          "asset": {
            "type": "image",
            "src": "assets/show/automation-monitor-failed.png",
            "caption": null,
            "autoplay": false
          }
        },
        {
          "id": "g",
          "layout": "image-stack",
          "eyebrow": "The automation monitor",
          "heading": "Failed, and dealt with",
          "body": "A failure someone has acknowledged. It stays on the board, ticked, rather than disappearing once it has been read.",
          "stackIndex": 6,
          "stackCount": 7,
          "asset": {
            "type": "image",
            "src": "assets/show/automation-monitor-failed-completed.png",
            "caption": null,
            "autoplay": false
          }
        }
      ]
    },
    {
      "id": "today",
      "order": 4,
      "title": "Today",
      "scale": 1.0,
      "heightened": false,
      "holdText": false,
      "stack": false,
      "subviews": [
        {
          "id": "main",
          "layout": "text-only",
          "eyebrow": "Part one",
          "heading": "Today, somebody retypes it",
          "body": "Open the sheet. Copy eleven values into the contract by hand. Export it, email it, chase the signature, file it. Every one of those steps is a chance to mistype something.",
          "asset": null
        }
      ]
    },
    {
      "id": "the-new-process",
      "order": 5,
      "title": "The new process",
      "scale": 1.0,
      "heightened": false,
      "holdText": false,
      "stack": false,
      "subviews": [
        {
          "id": "main",
          "layout": "title",
          "eyebrow": "Part two",
          "heading": "The new process",
          "body": "The same contract, and nobody retypes anything.",
          "asset": null
        }
      ]
    },
    {
      "id": "the-way-in",
      "order": 6,
      "title": "The way in",
      "scale": 1.0,
      "heightened": false,
      "holdText": false,
      "stack": false,
      "subviews": [
        {
          "id": "main",
          "layout": "animation",
          "eyebrow": "The way in",
          "heading": "Drop the sheet in a folder",
          "body": "SharePoint. Nothing new to learn.",
          "animation": "sharepoint-drop",
          "asset": null
        }
      ]
    },
    {
      "id": "extract-and-fill",
      "order": 7,
      "title": "Extract and fill",
      "scale": 1.0,
      "heightened": false,
      "holdText": false,
      "stack": false,
      "subviews": [
        {
          "id": "a",
          "layout": "asset-pair",
          "eyebrow": "Part two",
          "heading": "In, and out",
          "body": "Same eleven values, same reference.",
          "asset": {
            "type": "image",
            "src": "assets/show/company-information-sheet.png",
            "caption": "What went in",
            "autoplay": false
          },
          "assets": [
            {
              "type": "image",
              "src": "assets/show/company-information-sheet.png",
              "caption": "What went in",
              "autoplay": false
            },
            {
              "type": "image",
              "src": "assets/show/draft-contract.png",
              "caption": "What came out",
              "autoplay": false
            }
          ]
        },
        {
          "id": "b",
          "layout": "animation",
          "eyebrow": "Part two",
          "heading": "It reads the sheet and fills the contract",
          "body": "Eleven fields. Twenty-two places. No AI, and no guessing.",
          "animation": "extract-fill",
          "asset": null
        }
      ]
    },
    {
      "id": "the-approval",
      "order": 8,
      "title": "The approval",
      "scale": 1.0,
      "heightened": false,
      "holdText": false,
      "stack": false,
      "subviews": [
        {
          "id": "a",
          "layout": "single-asset",
          "eyebrow": "The first decision",
          "heading": "Everything happens in Teams",
          "body": "One card carrying the uploaded file, the draft it produced, and all eleven values. Nothing reaches the customer until somebody ticks the box.",
          "asset": {
            "type": "image",
            "src": "assets/show/teams-approval-card.png",
            "caption": null,
            "autoplay": false
          }
        },
        {
          "id": "b",
          "layout": "single-asset",
          "eyebrow": "The first decision",
          "heading": "And the values can be corrected",
          "body": "Edit the values, and every field opens. Whatever is in those boxes when you approve is what goes into the contract, whether or not you changed it.",
          "asset": {
            "type": "image",
            "src": "assets/show/teams-approval-editing.png",
            "caption": null,
            "autoplay": false
          }
        },
        {
          "id": "c",
          "layout": "single-asset",
          "eyebrow": "The first decision",
          "heading": "Or the same thing by email",
          "body": "A one-time link to a page that does what the card does. It exists because the Teams bot does not reach people outside the tenant, which we found with a real external uploader rather than by guessing.",
          "asset": {
            "type": "image",
            "src": "assets/show/email-approval-page.png",
            "caption": null,
            "autoplay": false
          }
        }
      ]
    },
    {
      "id": "the-signature",
      "order": 9,
      "title": "The signature",
      "scale": 1.0,
      "heightened": true,
      "holdText": false,
      "stack": false,
      "subviews": [
        {
          "id": "a",
          "layout": "single-asset",
          "eyebrow": "The second decision",
          "heading": "The customer opens a link",
          "body": "No account, no app, nothing to install. The whole contract to read, then four things to do, numbered.",
          "asset": {
            "type": "image",
            "src": "assets/show/signing-page.png",
            "caption": null,
            "autoplay": false
          }
        },
        {
          "id": "b",
          "layout": "single-asset",
          "eyebrow": "The second decision",
          "heading": "They sign by hand",
          "body": "Mouse, finger or stylus. The same page on a phone.",
          "asset": {
            "type": "image",
            "src": "assets/show/signing-draw.gif",
            "caption": null,
            "autoplay": false
          }
        },
        {
          "id": "c",
          "layout": "single-asset",
          "eyebrow": "The second decision",
          "heading": "Or upload a photograph of a signature",
          "body": "Ink on paper, photographed in bad light. The preview keeps the paper. The contract does not.",
          "asset": {
            "type": "image",
            "src": "assets/show/signing-upload.gif",
            "caption": null,
            "autoplay": false
          }
        },
        {
          "id": "d",
          "layout": "single-asset",
          "eyebrow": "The second decision",
          "heading": "And that is the agreement",
          "body": "Name typed, both boxes ticked, one button. It comes back with the reference, who signed, and when, to the second.",
          "asset": {
            "type": "image",
            "src": "assets/show/signing-approve.gif",
            "caption": null,
            "autoplay": false
          }
        }
      ]
    },
    {
      "id": "delivered",
      "order": 10,
      "title": "Delivered",
      "scale": 1.0,
      "heightened": false,
      "holdText": false,
      "stack": false,
      "subviews": [
        {
          "id": "a",
          "layout": "single-asset",
          "eyebrow": "What lands",
          "heading": "Both sides get the signed contract",
          "body": "One email each, one attachment: to the customer, and to the person who started it.",
          "asset": {
            "type": "image",
            "src": "assets/show/signed-contract.png",
            "caption": null,
            "autoplay": false
          }
        },
        {
          "id": "b",
          "layout": "single-asset",
          "eyebrow": "What lands",
          "heading": "And a fixed copy, if you want one",
          "body": "A storage mailbox, or the GISO team, can be added as a standing recipient on every contract.",
          "asset": {
            "type": "image",
            "src": "assets/show/signed-contract.png",
            "caption": null,
            "autoplay": false
          }
        }
      ]
    },
    {
      "id": "close",
      "order": 11,
      "title": "Close",
      "scale": 1.0,
      "heightened": false,
      "holdText": false,
      "stack": false,
      "subviews": [
        {
          "id": "main",
          "layout": "points",
          "eyebrow": "",
          "heading": "IMAGINE",
          "body": "",
          "items": [
            "Connected to CRM",
            "Connected to SwoDP",
            "Connected to the GISO ticket system"
          ],
          "asset": null
        }
      ]
    }
  ]
};
